### ISSUE TITLE
Improve publishing

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-delivery-sdk-ruby#22]
### Motivation

I noticed that the SDK is published under a personal account. From a long-term perspective, it'd be better to have it published under an organizational account. 

### Proposed solution

Create an organizational account (registered to developerscommunity@kentico.com) and publish the gem using this account.

**Comment by kentico-ericd** [comment]
devrel@kentico.com is added to the gem and can publish: https://rubygems.org/gems/kontent-delivery-sdk-ruby. Is that enough, or do you want to add developerscommunity@kentico.com as well?

**Comment by petrsvihlik** [comment]
it's enough
