### ISSUE TITLE
Bundle-audit flagging Nokogiri Vulnerability but SDK has locked version

### ISSUE THREAD

**Issue by ral3594** [Kentico/kontent-delivery-sdk-ruby#53]
Bundle-audit is flagging `Nokogiri` to be too low of a version in my project. However, when attempting to upgrade to `1.11.0`, it fails because the `kontent-delivery-sdk-ruby` is locking the version as seen below:

```
kontent-delivery-sdk-ruby (~> 2) was resolved to 2.0.12, which depends on
      nokogiri (>= 1.8.4, ~> 1.10.0)
```

Can this be updated as Nokogiri has been updated?

Link to Nokogiri security issue: https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-vr8q-g5c7-m54m

**Comment by kentico-ericd** [comment]
Hello, sorry for the delay! Does v2.0.19 resolve the issue?
