### ISSUE TITLE
kcl-4508 introduce new system property (workflow_step) in item object

### ISSUE THREAD

**Issue by Sevitas** [Kentico/kontent-delivery-sdk-ruby#55]
### Motivation

Introduces new system property 'workflow_step' representing codename of the workflow step, an item is assigned to. Items can be filtered out based on this property

### Proposed solution

Introduce new property to system object of items. Components should not contain this property.

**Comment by kentico-ericd** [comment]
Hello @Sevitas !

Since the system attributes are dynamically parsed from the JSON response, the "workflow_step" attribute already appeared without any changes. I did however add a test to ensure it works 👍
