### ISSUE TITLE
Unhandled exception when `depth` size is not correctly set

### ISSUE THREAD

**Issue by BenjaminDigeon** [Kentico/kontent-delivery-sdk-ruby#56]
When the `depth` is not correctly set and we try to access a `linked_item` the gem raise a unhandled exception.

```
undefined method '[]' for nil:NilClass
```

that occurs in `lib/delivery/resolvers/linked_item_resolver.rb` at 

```ruby
def resolve_item(codename)
  item = @modular_content.values.find { |i| i['system']['codename'] == codename }
  ContentItem.new JSON.parse(JSON.generate(item)), @content_link_url_resolver, @inline_content_item_resolver, self
end
```

The `codename` is not inside the `modular_content` so the `find` method return `nil`

It's easily fix by increasing the `depth` size of the request but that would be better to raise a custom exception.

### Test environment

- Ruby 2.7
- kontent-delivery-sdk-ruby 2.0.22

**Comment by kentico-ericd** [comment]
Hey @BenjaminDigeon!

Thanks for the bug report 👍 I'm currently having some permission issue with the repo (embarrassing) so I couldn't push the changes here, but I did just package up `2.0.24` of the gem and push it live. Now, if the `depth` is insufficient (e.g. 0), calling `get_links('my_element')` will return an empty array.
